export { default as About } from './About';
export { default as Admin } from './Admin';
export { default as Account } from './Account';
export { default as Contact } from './Contact';
export { default as Home } from './Home';
export { default as NoPage } from './NoPage';
export { default as Authors } from './Authors';
export { default as Colleges } from './Colleges';
export { default as Disciplines } from './Disciplines';
